name: Bump project versions
on:
  push:
    branch:
      - 'develop'
jobs:
  bump-versions:
    if: "!contains(github.event.head_commit.author.name, 'GITHUBACTION')"
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump versions
        run: |
          git config user.name "GITHUBACTION" |
          $GITHUB_WORKSPACE/.github/scripts/bump-versions.sh 
          
        env:
          AFTER_COMMIT_SHA: ${{ github.event.after }}
          BEFORE_COMMIT_SHA: ${{ github.event.before }}